const mongoose = require("mongoose");

const blogSchema = new mongoose.Schema({
  title: String,
  description: String,
  category: String,
  subFive: String,
  subFour: String,
  subOne: String,
  subThree: String,
  subTwo: String,
  desFive1: String,
  desFive2: String,
  desFive3: String,
  desFive4: String,
  desFour1: String,
  desFour2: String,
  desFour3: String,
  desFour4: String,
  desOne1: String,
  desOne2: String,
  desOne3: String,
  desOne4: String,
  desThree1: String,
  desThree2: String,
  desThree3: String,
  desThree4: String,
  desTwo1: String,
  desTwo2: String,
  desTwo3: String,
  desTwo4: String,
  writer: String,
  profession: String,
  fb: String,
  ig: String,
  tw: String,
  lnk: String,
  date: String,
  love: Number,
  followers: Number,
  sub1image:String,
  sub2image:String,
  sub3image:String,
  sub4image:String,
  sub5image:String,
  propic:String,
  comments: [{}],
  cred:
  {
    type: mongoose.Schema.Types.ObjectId,
    ref: "cred",
  },
});

const blogModel = mongoose.model("blog", blogSchema);

module.exports = blogModel;
